### Get all products
GET http://localhost:3000/api/products

### Get Single product
GET http://localhost:3000/api/products/2

### Create new product
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "title": "phone",
  "description": "about phone",
  "price": 400
}

### Update product
PUT http://localhost:3000/api/products/1
Content-Type: application/json

{
  "title": "update laptop",
  "price": 544

}

### Delete product
DELETE http://localhost:3000/api/products/1