### Register
POST  http://localhost:3000/api/users/auth/register
Content-Type: application/json

{
  "email":"reem@gmail.com",
  "password": "123456"
}

### Get Single users
GET http://localhost:3000/api/users/1